name: Move new issues into Triage

on:
  issues:
    types: [labeled]

permissions: write-all

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        if: contains(github.event.issue.labels.*.name, 'Leads team')
        uses: peter-evans/create-or-update-project-card@v3
        with:
          project-location: timwright12
          project-number: 2
          column-name: Done
