name: Move new issues into Triage

on:
  issues:
    types: [labeled]

jobs:
  automate-project-columns:
    if: contains(github.event.issue.labels.*.name, 'Leads team')
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Mobile SOS Board
          column: Backlog
          repo-token: ${{ secrets.GITHUB_TOKEN }}
